services:
  proxy:
    image: jc21/nginx-proxy-manager:2.12.6
    container_name: nginx-proxy-manager
    restart: unless-stopped
    volumes:
      - /opt/docker_apps/Proxy/nginxproxy_docker_data:/data
      - /opt/docker_apps/Proxy/nginxproxy_docker_encrypt:/etc/letsencrypt
    ports:
      - "443:443"    # HTTPS
      - "80:80"      # HTTP
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment: 
      - TZ=${TIMEZONE}
    networks:
      - proxy_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m

networks:
  proxy_net:
    driver: bridge
    name: proxy_network