services:
    portainer:
      image: portainer/portainer-ce:latest
      container_name: portainer
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./portainer_docker_conf:/data
      restart: unless-stopped
      networks:
        - proxy_network
      environment:
        - TZ=${TIMEZONE}
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 30s

networks:
  proxy_network:
    external: true