services:
    portainer:
      image: portainer/portainer-ce:latest
      container_name: portainer
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./portainer_docker_conf:/data
      restart: unless-stopped
      networks:
        - proxy_network
      environment:
        - TZ=${TIMEZONE}

networks:
  proxy_network:
    external: true